name: Deploy to Server

on:
  push:
    branches: [master]

concurrency:
  group: "deploy"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --no-frozen-lockfile
      - run: pnpm build

      - name: Create target directory on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 8.148.176.202
          username: carrot
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: mkdir -p /home/carrot/zero-to-tech/dist

      - name: Deploy dist to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 8.148.176.202
          username: carrot
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: dist/
          target: /home/carrot/zero-to-tech/
          strip_components: 1
          rm: true
