name: Deploy to Server

on:
  push:
    branches: [master]

concurrency:
  group: "deploy"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --no-frozen-lockfile
      - run: pnpm build

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: 8.148.176.202
          REMOTE_USER: carrot
          SOURCE: dist/
          TARGET: /home/carrot/zero-to-tech/dist/
          ARGS: -avz --delete
